/* Editorial synthesis. The practical examples are original proposals, not quotations. */
const SOURCES = {
  evagrio:{kind:'Tradición cristiana',title:'Evagrio Póntico · Praktikós, 6–14',url:'https://evagriusponticus.net/cpg2430/cpg2430.eng.1990.dysinger.html',note:'Mapa ascético de ocho pensamientos, escrito para monjes. Sirve para observar patrones; no es una clasificación clínica. Recogemos este aporte concreto, no el conjunto de sus posiciones doctrinales.'},
  casiano:{kind:'Padres de la Iglesia',title:'Juan Casiano · Conferencia V, 2–4 y 13–14',url:'https://www.newadvent.org/fathers/350805.htm',note:'Los patrones se relacionan y el trabajo puede centrarse en el que más nos afecta. Adaptamos esa atención a la vida cotidiana; no trasladamos las austeridades monásticas.'},
  virtud:{kind:'Iglesia católica',title:'Catecismo · 1803–1811 y 1822–1829',url:'https://www.vatican.va/archive/catechism_sp/p3s1c1a7_sp.html',note:'La virtud dispone a hacer el bien. La práctica y la perseverancia cooperan con la gracia; la caridad orienta el camino hacia Dios y el prójimo.'},
  tentacion:{kind:'Iglesia católica',title:'Catecismo · 2846–2849',url:'https://www.vatican.va/archive/catechism_sp/p4s2a3_sp.html',note:'Distingue entre ser tentado y consentir. La vigilancia se acompaña de oración; la aparición de un pensamiento no equivale a una falta.'},
  volver:{kind:'Iglesia católica',title:'Catecismo · 1428–1431 y 1451–1460',url:'https://www.vatican.va/archive/catechism_sp/p2s2c2a4_sp.html',note:'La conversión es continua. Arrepentimiento, reconciliación y reparación del daño pertenecen a la vida cristiana. Una anotación en la app no sustituye la confesión.'},
  epicteto:{kind:'Filosofía estoica',title:'Epicteto · Enquiridión, 1 y 34',url:'https://classics.mit.edu/Epictetus/epicench.html',note:'Distinguir la propia respuesta de lo que no se controla y dar tiempo antes de seguir un impulso. Aquí se usa como ejercicio de atención, no como doctrina católica.'},
  marco:{kind:'Filosofía estoica',title:'Marco Aurelio · Meditaciones, V, 9',url:'https://classics.mit.edu/Antoninus/meditations.5.five.html',note:'Invita a regresar a la práctica después de actuar mal. Esta afinidad práctica no identifica el estoicismo con la fe cristiana.'},
  planes:{kind:'Psicología',title:'Gollwitzer y Sheeran · Implementation Intentions',url:'https://dccps.nci.nih.gov/BRP/constructs/implementation_intentions/goal_intent_attain.pdf',note:'Vincular una situación reconocible con una respuesta prevista puede ayudar a llevar las intenciones a la acción. Los efectos dependen del contexto; no garantiza resultados personales.'},
  habitos:{kind:'Investigación empírica',title:'Lally y colaboradores · Formación de hábitos (2010)',url:'https://openresearch.surrey.ac.uk/esploro/outputs/99783513802346',note:'Estudio de conductas cotidianas repetidas en un contexto estable. La automaticidad varió mucho y una omisión aislada no anuló el proceso. Siete días permiten revisar, no prometen formar una virtud ni un hábito.'},
  compasion:{kind:'Investigación experimental',title:'Breines y Chen · Autocompasión y mejora (2012)',url:'https://pubmed.ncbi.nlm.nih.gov/22645164/',note:'En cuatro experimentos, responder con autocompasión a un error favoreció indicadores de motivación para mejorar. No demuestra por sí solo cambios duraderos ni elimina la responsabilidad por el daño.'}
};
const CHALLENGES = {
  ira:{title:'Responder con mansedumbre',virtue:'Mansedumbre y justicia',cue:'Noto que voy a responder con dureza',action:'Pido una pausa y acuerdo cuándo retomar la conversación con respeto',minimum:'Digo «necesito un momento» antes de contestar',support:'Evito abrir conversaciones difíciles cuando estoy agotado',recovery:'Reconozco lo que dije, pido perdón sin excusas y retomo el asunto sin atacar',guide:'La pausa sirve para hablar mejor, no para castigar con silencio. Puedes poner límites y buscar protección ante el maltrato.',prayer:'Señor, ayúdame a defender el bien sin herir.',refs:['evagrio','virtud','epicteto','planes']},
  acedia:{title:'Permanecer en un bien pequeño',virtue:'Perseverancia',cue:'Llega el momento del deber que estoy evitando',action:'Ofrezco a Dios la tarea y hago el primer gesto durante cinco minutos',minimum:'Preparo el material y hago un gesto de un minuto',support:'Dejo preparado lo necesario y aparto una distracción',recovery:'Reduzco la tarea, busco qué me bloqueó y vuelvo en la próxima ocasión',guide:'Cinco minutos es una ayuda práctica elegida aquí, no una dosis científica. Antes de exigirte más, atiende el cansancio; procrastinar no demuestra acedia.',prayer:'Señor, recibe este pequeño acto de fidelidad.',refs:['evagrio','casiano','planes','habitos']},
  gula:{title:'Comer con atención y gratitud',virtue:'Templanza',cue:'Me siento a una comida del día',action:'Doy gracias y dejo la pantalla para prestar atención a la comida',minimum:'Dejo el móvil a un lado al empezar',support:'Organizo una comida tranquila y suficiente cuando me es posible',recovery:'Retomo en la próxima comida sin castigos ni compensaciones',guide:'El reto no consiste en pasar hambre, restringir cantidades ni compensar lo comido. Si la comida te provoca angustia o pérdida de control, busca ayuda especializada.',prayer:'Señor, gracias por el alimento y por quienes lo hacen posible.',refs:['evagrio','virtud','habitos']},
  lujuria:{title:'Cuidar la mirada y el vínculo',virtue:'Castidad y respeto',cue:'Voy a abrir un contenido que he decidido evitar',action:'Cierro el acceso y paso a una actividad concreta acorde con mis valores',minimum:'Cierro la pantalla y cambio de lugar',support:'Retiro un acceso que me facilita repetir ese comportamiento',recovery:'Identifico la ocasión, ajusto el entorno y busco acompañamiento si lo necesito',guide:'Tener deseo o un pensamiento involuntario no equivale a consentir. Cuida la dignidad propia y ajena; no conviertas el reto en vigilancia continua de la mente.',prayer:'Señor, enséñame a mirar y amar a las personas con respeto.',refs:['evagrio','tentacion','epicteto','planes']},
  avaricia:{title:'Compartir con prudencia',virtue:'Generosidad',cue:'Termino de organizar mis responsabilidades del día',action:'Elijo una ayuda concreta que puedo ofrecer sin descuidar mis obligaciones',minimum:'Pregunto a alguien cercano qué ayuda necesita',support:'Reservo un pequeño espacio de tiempo; no necesito gastar dinero',recovery:'Reconozco el apego o el miedo y elijo una ayuda proporcionada',guide:'Ahorrar, prever gastos y proteger a tu familia no son avaricia. Compartir tiempo o atención también puede ser generoso.',prayer:'Señor, ayúdame a administrar bien y compartir lo recibido.',refs:['evagrio','virtud','planes']},
  tristeza:{title:'Dejarme acompañar',virtue:'Esperanza',cue:'Llega mi pausa de la tarde',action:'Nombro cómo estoy y busco un pequeño contacto con alguien de confianza',minimum:'Envío un mensaje honesto pidiendo compañía',support:'Elijo con antelación a quién puedo acudir',recovery:'Retomo el contacto sin reprocharme un día difícil',guide:'La tristeza, el duelo y la depresión no son faltas morales. Esta propuesta cuida el vínculo y no mide si consigues sentirte bien. Si el malestar persiste o dificulta tu vida, pide ayuda profesional.',prayer:'Señor, acompáñame en lo que hoy me pesa.',refs:['virtud','compasion']},
  vanagloria:{title:'Hacer el bien con libertad',virtue:'Humildad y caridad',cue:'Veo una pequeña necesidad en casa o en el trabajo',action:'Ayudo sin buscar después una reacción o elogio',minimum:'Hago una ayuda sencilla sin anunciarla',support:'Elijo un servicio pequeño y sostenible',recovery:'Reconozco la búsqueda de aprobación y vuelvo a la persona a la que puedo servir',guide:'Agradecer un reconocimiento y comunicar tu trabajo es legítimo. No ocultes abusos ni renuncies a pedir un trato justo.',prayer:'Señor, que mi atención vuelva a la persona que necesita ayuda.',refs:['evagrio','virtud','epicteto']},
  soberbia:{title:'Aprender a recibir ayuda',virtue:'Humildad',cue:'Me encuentro con una dificultad que no sé resolver',action:'Hago una pregunta concreta y escucho antes de justificarme',minimum:'Reconozco «esto no lo sé»',support:'Identifico a una persona fiable a quien consultar',recovery:'Reviso mi reacción, agradezco lo útil y pido ayuda de nuevo',guide:'Humildad no significa despreciarte ni aceptar toda crítica como verdadera. Puedes discernir, disentir y poner límites.',prayer:'Señor, gracias por lo recibido; enséñame a seguir aprendiendo.',refs:['evagrio','virtud','compasion']}
};
const PATH_STEPS = [
 {title:'Elegir hacia dónde caminar',text:'Propón un bien concreto para esta semana: hablar con respeto, estar presente o cumplir un deber. Pregunta para quién lo haces y qué virtud quieres practicar. Puedes repetir el mismo reto varias semanas.',practice:'Escribe una acción que dependa de ti, no el resultado que otra persona debería darte.',refs:['virtud','epicteto']},
 {title:'Preparar el terreno',text:'Descanso, alimento, compañía y un entorno manejable forman parte del camino. No necesitas resolver toda tu vida antes de empezar. Elige una ayuda que haga posible tu práctica.',practice:'Retira una distracción o deja preparado el primer paso. Si estás agotado, reduce la exigencia y atiende lo necesario.',refs:['planes','habitos']},
 {title:'Reconocer y responder',text:'Cuando aparezca la situación prevista, nombra lo que pasa sin etiquetarte. Un pensamiento, una emoción y una elección son cosas distintas. Pide ayuda a Dios y realiza la respuesta que elegiste.',practice:'Usa tu plan: «Cuando ocurra esto, haré esto otro». Si hoy no cabe todo, usa tu versión mínima.',refs:['evagrio','tentacion','planes']},
 {title:'Volver después de una caída',text:'Reconoce lo sucedido sin insultarte. Detén el daño, repara lo reparable y pide perdón cuando corresponda. Mira qué facilitó la caída y prepara un regreso pequeño. Busca la reconciliación sacramental y acompañamiento según tu situación.',practice:'No esperes al lunes ni dupliques la exigencia para compensar. Vuelve en la próxima ocasión adecuada.',refs:['volver','marco','compasion']},
 {title:'Revisar y seguir',text:'Al cerrar tus siete días, da gracias por un bien concreto y mira las dificultades con verdad. Decide si mantener, simplificar o cambiar la práctica. Una semana no es un examen de tu valor ni una medida de santidad.',practice:'Conserva lo que ayuda y cambia un obstáculo. Repetir un reto puede tener más sentido que buscar uno nuevo.',refs:['habitos','casiano','virtud']}
];
