const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'chrome'});let page;
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,reducedMotion:'reduce',timezoneId:'Europe/Madrid'});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const url=`http://127.0.0.1:${server.address().port}/`;fs.mkdirSync(path.join(__dirname,'artifacts'),{recursive:true});const shot=async n=>page.screenshot({path:path.join(__dirname,'artifacts',n+'.png')});const fit=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No horizontal overflow');
 await page.goto(url);await page.waitForFunction(()=>typeof state!=='undefined'&&state.schemaVersion===3);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await shot('welcome');await fit();
 // Existing personal data are retained and used as a draft, never silently enrolled.
 const legacy={front:'ira',weapon:'Pedir una pausa concreta',question:'Mi pregunta personal',reviews:Array.from({length:25},(_,i)=>({date:'2026-09-01T12:00:00Z',focus:'Reflexión '+i,progress:'Un paso'})),lastAction:'Llamar a mi familia',unknownField:{keep:true}};
 await page.evaluate(x=>{localStorage.removeItem('reglaApp.before-v3');localStorage.setItem('reglaApp',JSON.stringify(x));},legacy);await page.reload();
 assert.equal(await page.evaluate(()=>activeChallenge()),null);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('reglaApp.before-v3'))),legacy);
 await page.locator('#challengeHero button').click();assert.equal(await page.locator('#setupWeapon').inputValue(),legacy.weapon);await page.locator('#setupName').fill('Escuchar antes de responder');await page.locator('#setupCue').fill('Noto que voy a interrumpir');await page.locator('#setupMinimum').fill('Escucho una frase completa');await page.locator('#saveChallengeButton').click();await page.waitForTimeout(120);
 assert.equal(await page.evaluate(()=>state.reviews.length),25);assert.equal(await page.evaluate(()=>state.unknownField.keep),true);assert.equal(await page.evaluate(()=>dayNumber(state.challenge.end)-dayNumber(state.challenge.start)),6);
 await shot('today');await page.locator('#dailyNote').fill('Necesito dormir antes de discutir. <script>no()</script>');await page.getByRole('button',{name:'Hice lo mínimo',exact:true}).click();
 const id=await page.evaluate(()=>state.challenge.id);await page.reload();assert.equal(await page.getByRole('button',{name:'Hice lo mínimo',exact:true}).getAttribute('aria-pressed'),'true');assert.match(await page.locator('#dailyNote').inputValue(),/Necesito dormir/);
 await page.locator('#dailyNote').fill('Nota automática');await page.locator('[data-screen="ways"]').click();await page.locator('[data-screen="today"]').click();assert.equal(await page.locator('#dailyNote').inputValue(),'Nota automática');await page.locator('#dailyNote').fill('Necesito dormir antes de discutir.');
 await page.locator('[data-screen="ways"]').click();assert.equal(await page.locator('.week-day').count(),7);await shot('week');
 await page.getByRole('button',{name:'Ajustar este reto',exact:true}).click();await page.locator('#setupWeapon').fill('Pido una pausa y concreto cuándo hablar');
 await page.evaluate(()=>{window.realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='reglaApp')throw new DOMException('Full','QuotaExceededError');return window.realSetItem.call(this,k,v);};});
 await page.locator('#saveChallengeButton').click();assert.equal(await page.locator('#sheet').isVisible(),true);assert.equal(await page.evaluate(()=>state.challenge.action),'Pedir una pausa concreta');await page.evaluate(()=>{Storage.prototype.setItem=window.realSetItem;});
 await page.locator('#saveChallengeButton').click();await page.waitForTimeout(100);
 assert.equal(await page.evaluate(()=>state.challenge.id),id);assert.equal(await page.evaluate(()=>state.challenge.revisions.length),1);assert.equal(await page.evaluate(()=>Object.keys(state.challenge.logs).length),1);
 await page.locator('[data-screen="today"]').click();await page.getByRole('button',{name:/Quiero volver/}).click();await shot('return');await page.locator('#recoveryMark').click();await page.waitForTimeout(100);assert.equal(await page.getByRole('button',{name:'He retomado',exact:true}).getAttribute('aria-pressed'),'true');assert.match(await page.locator('#dailyNote').inputValue(),/Necesito dormir/);
 await page.getByRole('button',{name:/Necesito margen/}).click();await page.locator('[data-fatigue="body"]').click();assert.match(await page.locator('#fatigueResult').textContent(),/Fatiga física/);await page.goBack();await page.waitForTimeout(100);assert.equal(await page.locator('#sheet').isVisible(),false);
 await page.getByRole('button',{name:/Empezar con cinco minutos/}).click();await page.locator('#nextAction').fill('Escuchar');await page.getByRole('button',{name:'Empezar cinco minutos',exact:true}).click();assert.equal(await page.locator('#timerBox').isVisible(),true);await page.getByRole('button',{name:'Detener',exact:true}).click();assert.equal(await page.locator('#timerBox').isVisible(),false);await page.locator('#sheet .close').click();await page.waitForTimeout(100);
 await page.locator('[data-screen="review"]').click();await page.locator('[name="progress"]').fill('He pedido una pausa');await page.locator('[name="learning"]').fill('Menos discusión al descansar');await page.locator('[name="focus"]').fill('Repetir mi reto');await page.getByRole('button',{name:'Guardar reflexión',exact:true}).click();assert.equal(await page.evaluate(()=>state.reviews.length),26);assert.equal(await page.evaluate(()=>state.reviews[0].challengeId),id);
 // Finish / repeat keeps the prior week, notes, revisions and reviews.
 await page.locator('[data-screen="ways"]').click();await page.getByRole('button',{name:/Cerrar y proponer otra semana/}).click();assert.equal(await page.locator('#setupWeapon').inputValue(),'Pido una pausa y concreto cuándo hablar');await page.locator('#saveChallengeButton').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>state.challenges.length),1);assert.equal(await page.evaluate(()=>state.challenges[0].id),id);assert.equal(await page.evaluate(()=>Object.keys(state.challenges[0].logs).length),1);assert.notEqual(await page.evaluate(()=>state.challenge.id),id);
 // Expired week cannot be marked as today. No automatic replacement.
 await page.evaluate(()=>{state.challenge.start=addDays(localDay(),-8);state.challenge.end=addDays(state.challenge.start,6);persist();});await page.reload();assert.match(await page.locator('#dailyPractice').textContent(),/Tu semana terminó/);assert.equal(await page.locator('#dailyNote').count(),0);
 assert.equal(await page.evaluate(()=>addDays('2026-10-23',6)),'2026-10-29');
 await page.locator('[data-screen="manual"]').click();await page.locator('#manualSearch').fill('epicteto');assert.ok(await page.locator('#manual .manual-section:visible').count()>0);await page.locator('#manualSearch').fill('zzzzzz');assert.equal(await page.locator('#guideEmpty').isVisible(),true);await page.locator('#manualSearch').fill('');await shot('guide');
 for(const width of [320,390,430,900]){await page.setViewportSize({width,height:844});for(const screen of ['today','ways','review','manual']){await page.evaluate(s=>showScreen(s),screen);await fit();}}
 await page.setViewportSize({width:320,height:844});await page.evaluate(()=>showScreen('ways'));await page.locator('.idea').first().click();await fit();await page.locator('#sheet .close').click();await page.waitForTimeout(100);
 // Other same-origin apps keep their caches during activation.
 await page.evaluate(async()=>{await caches.open('another-app-keep');});
 await context.setOffline(true);await page.reload();await page.locator('[data-screen="manual"]').click();assert.ok(await page.locator('.source-card').count()>=9);await page.locator('[data-screen="review"]').click();assert.equal(await page.evaluate(()=>state.reviews.length),26);assert.equal(await page.evaluate(async()=>(await caches.keys()).includes('another-app-keep')),true);
 assert.deepEqual(errors,[]);
 await context.setOffline(false);
 // Malformed records should remain recoverable, without breaking the interface.
 await page.evaluate(()=>{localStorage.setItem('reglaApp',JSON.stringify({reviews:{old:'keep'},challenge:{broken:true},challenges:'keep'}));});await page.reload();assert.equal(await page.evaluate(()=>state.legacyReviews.old),'keep');assert.equal(await page.evaluate(()=>state.legacyChallenge.broken),true);assert.equal(await page.evaluate(()=>state.legacyChallenges),'keep');
 console.log('PASS: legacy preservation, weekly creation/edit/archive, daily return, notes, reviews, history, search, mobile layouts and offline.');
}catch(e){if(page)await page.screenshot({path:path.join(__dirname,'artifacts','failure.png')}).catch(()=>{});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
